version: '2'
services:
### LDAP Server
  ladp:
    container_name: ldap-server
    image: osixia/openldap:latest
    ports:
    - 389:389
    - 636:636
    expose:
    - 389
    - 636
    environment:
      LDAP_ORGANISATION: "RDProd"
      LDAP_DOMAIN: "ldap.rdprod.org"
      LDAP_ADMIN_PASSWORD: "05Darsh@ne" 
      LDAP_TLS: "false"
      LDAP_BASE_DN: ""
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
    networks:
      - elastic
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config/:/etc/ldap/slapd.d
  ldap_server_admin:
    container_name: ldap_server_admin
    image: osixia/phpldapadmin:0.7.2
    ports:
      - 8090:80
    expose:
      - 8090
    networks:
      - elastic
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
      PHPLDAPADMIN_HTTPS: 'false'
#  volumes:
#    ldap_data:
#    ldap_config:

### Docker Registry
  registry:
    container_name: registry
    image: registry:latest
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_SECRET: '05Darsh@ne'
    volumes:
      - ./registry/auth:/auth:rw
      - ./registry/data:/data:rw
      - ./registry/config.yml:/etc/docker/registry/config.yml:rw
    networks:
      - elastic

  docker-registry-ui:
    container_name: registry-iu
    image: joxit/docker-registry-ui:latest
    ports:
      - "8086:80"
    expose:
      - "8086"
    environment:
      - REGISTRY_URL=http://registry.rdprod.org/
      - DELETE_IMAGES=true
    restart: always
    depends_on: 
      - registry
    networks:
      - elastic


### Uptime Kuma
  uptime:
    container_name: uptime
    image: louislam/uptime-kuma:1
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: always
    networks:
      - elastic

### Grafana
  grafana:
    container_name: grafana
    image: darshaner/grafana:8.5.2
    restart: always
    logging:
      driver: json-file
    networks:
      - elastic
    ports:
      - "3000:3000"

### Elastic Search 
  elasticsearch:
    container_name: es
    image: darshaner/elasticsearch:8.5.2
    restart: always
    logging:
      driver: json-file
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - cluster.name=es-rajabaly
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.enabled=true
        #- xpack.security.autoconfiguration.enabled=true
        #- xpack.security.enrollment.enabled=true
        # volumes:
        #   - /opt/esdata:/usr/share/elasticsearch/data
        #   - /opt/elastic:/usr/share/elasticsearch
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"

### Kibana
  kibana:
    container_name: kibana
    image: darshaner/kibina:8.5.2
    restart: always
    logging:
      driver: json-file
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
        #  - 'elasticsearch.serviceAccountToken:"AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuX2tpYmFuYTozRlBPaHp3elM5V0xTWm5sZ1M4VlR3"'
        #  - elasticsearch.username= "elastic"
        #  - elasticsearch.password= "Vc1*QsWH=ULjeP3CfmQ3"
    volumes:
      - ./kbdata:/usr/share/kibana/data:rw
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

        #### Homebridge
        #  homebridge:
        #    container_name: homebridge
        #    image: oznu/homebridge:latest
        #    restart: always
        #    logging:
        #      driver: json-file
        #      options:
        #        max-size: "10mb"
        #        max-file: "7"
        #    volumes:
        #      - /var/lib/homebridge:/homebridge:rw
        #    networks:
        #      - elastic
        #    ports:
        #      - "8581:8581"
        #      - "34164:34164"
        #      - "42585:42585"
        #      - "53908:53908"
        #    expose:
        #      - "34164/tcp"
        #      - "42585/tcp"
        #      - "53908/tcp"

### Transmission
#    transmission:
#      image: lscr.io/linuxserver/transmission:latest
#      container_name: transmission
#      environment:
#        - PUID=1000
#        - PGID=1000
#        - TZ=Etc/UTC
#        - TRANSMISSION_WEB_HOME= #optional
#        - USER= #optional
#        - PASS= #optional
#        - WHITELIST= #optional
#        - PEERPORT= #optional
#        - HOST_WHITELIST= #optional
#      volumes:
#        - /path/to/data:/config
#        - /path/to/downloads:/downloads
#        - /path/to/watch/folder:/watch
#      ports:
#        - 9091:9091
#        - 51413:51413
#        - 51413:51413/udp
#      restart: unless-stopped

### Docker Networks
networks:
  elastic:
    driver: bridge

### Docker Volumes
volumes:
  esdata:
    driver: local
  kbdata:
    driver: local
  elastic:
    driver: local
  registry:
    driver: local
  ldap:
    driver: local
  uptime-kuma:
    driver: local
