app: "rdprod-lab-services"
docker_host_runner_lab:
  app: "rdprod-lab-services"
  static_cf_services:
    rdlab01:
      proxied: false

  services:
### Lab Containers
    grafana:
      container_name: grafana
      hostname: grafana
      image: grafana/grafana:latest
      restart: always
      mem_limit: 512m
      mem_reservation: 256M
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.122"
      ports:
        - "3000:3000"
      expose:
        - "3000"
      #environment:
      volumes:
        - ./grafdata/grafana:/usr/share/grafana:rw
      depends_on:
        - es
      proxied: true

    es:
      container_name: es
      hostname: es
      image: elasticsearch:8.6.2
      restart: always
      mem_limit: 2048m
      mem_reservation: 512M
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.123"
      ports:
        - "9200:9200"
      expose:
        - "9200"
      healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3
      environment:
        - cluster.name=es-rajabaly
        - xpack.security.enabled=false
        - xpack.license.self_generated.type=basic
        - "discovery.type=single-node"
        - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
        - bootstrap.memory_lock=true
      volumes:
        - ./esdata/elasticsearch/:/usr/share/elasticsearch/:rw
      proxied: false

    kibana:
      container_name: kibana
      hostname: kibana
      image: kibana:8.6.2
      restart: always
      mem_limit: 1024m
      mem_reservation: 256M
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.124"
      ports:
        - "5601:5601"
      expose:
        - "5601"
      environment:
        - ELASTICSEARCH_HOSTS=http://es:9200
      volumes:
        - ./kbdata:/usr/share/kibana/data:rw
      depends_on:
        - es
      proxied: true

    homeassistant:
      container_name: homeassistant
      hostname: homeassistant
      image: "ghcr.io/home-assistant/home-assistant:stable"
      restart: always
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.125"
      ports:
        - "8123:8123"
      expose:
        - "8123"
      volumes:
        - ./homeassist/:/config:rw
        - /etc/localtime:/etc/localtime:ro
      privileged: true
      proxied: false
    
    dns:
      container_name: dns
      hostname: dns
      image: sameersbn/bind:latest
      restart: always
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.127"
      ports: 
        - "53:53/tcp"
        - "53:53/udp"
      expose:
        - "53"
      environment: 
        - "BIND_UID=1000"
        - "BIND_GID=1000"
      volumes: 
        - ./dns/bind:/data:rw
      proxied: false

  networks:
    elastic: 
      driver: macvlan
      driver_opts: 
        parent: "{{ ethernet_interface }}"
      ipam:
        config:
          - subnet: 192.168.0.0/24
            gateway: 192.168.0.254

  volumes:
    kbdata:
      driver: local
    uptime-kuma:
      driver: local
    esdata:
      driver: local
    vaultdata:
      driver: local

  #  vault:
  #    container_name: vault
  #    image: vault:latest
  #    restart: always
  #    logging:
  #      driver: json-file
  #    networks:
  #      elastic:
  #        ipv4_address: 192.168.0.8
  #    ports: 
  #      - "8200:8200"
  #    expose:
  #      - "8200"
  #    environment:
  #      #- VAULT_DEV_ROOT_TOKEN_ID='05Darsh@ne'
  #      - VAULT_CLUSTER_ADDR='http://vault.rdprod.org:8200'
  #      - VAULT_API_ADDR='http://vault.rdprod.org/v1'
  #    volumes: 
  #      - ./vaultdata:/vault:rw
  #    cap_add:
  #      - IPC_LOCK
  #    command: server 


  #  at-runner:
  #    container_name: at-runner
  #    image: at-runner:latest
  #    restart: always
  #    logging:
  #      driver: json-file
  #    networks:
  #      elastic:
  #        ipv4_address: "192.168.0.69"
  #    ports:
  #      - "22:22"
  #    expose:
  #      - "22"
  #    volumes:
  #      - ./homebridge/var/lib/homebridge:/homebridge:rw