image_name: "at-runner"
image_version: "latest"
#docker_registry: "https://registry.lab.un2ground.fr"
docker_registry: "registry.rdprod.org:5000"
registry_username: "darshaner"
registry_password: "{{ vault_registry_password }}"
build_dir: "/tmp/build"