---

- name: Add Services in Cloudflare
  community.general.cloudflare_dns:
    zone: "{{ cf_zone }}"
    record: "{{ item.key }}.{{ cf_zone }}"
    type: "A"
    value: "{{ public_ip }}"
    ttl: "{{ cf_ttl }}"
    proxied: "{{ item.value.proxied }}"
    state: "present"
    api_token: "{{ cf_token }}"
  loop: "{{ services | dict2items }}"
  
...