app: "rdprod-services"
folder: "opt"
services:
  uptime:
    container_name: uptime
    image: louislam/uptime-kuma:beta
    restart: always
    logging:
      driver: json-file
    networks:
      elastic:
        ipv4_address: "192.168.0.63"
    ports:
      - "3001:3001"
    expose:
      - "3001"
    volumes:
      - ./uptime-kuma:/app/data:rw
    depends_on: 
      - kibana

  grafana:
    container_name: grafana
    image: darshaner/grafana:8.5.2
    restart: always
    logging:
      driver: json-file
    networks:
      elastic:
        ipv4_address: "192.168.0.68"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    #environment:
    #volumes:
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: es
    image: darshaner/elasticsearch:8.5.2
    restart: always
    logging:
      driver: json-file
    networks:
      elastic:
        ipv4_address: "192.168.0.65"
    ports:
      - "9200:9200"
    expose:
      - "9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - cluster.name=es-rajabaly
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - bootstrap.memory_lock=true

  kibana:
    container_name: kibana
    image: darshaner/kibina:8.5.2
    restart: always
    logging:
      driver: json-file
    networks:
      elastic:
        ipv4_address: "192.168.0.66"
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    volumes:
      - ./kbdata:/usr/share/kibana/data:rw
    depends_on:
      - elasticsearch

  homebridge:
    container_name: homebridge-docker
    image: oznu/homebridge:latest
    restart: always
    logging:
      driver: json-file
    networks:
      elastic:
        ipv4_address: "192.168.0.67"
    ports:
      - "8581:8581"
    expose:
      - "8581"
    volumes:
      - ./homebridge/var/lib/homebridge:/homebridge:rw
        
#  at-runner:
#    container_name: at-runner
#    image: at-runner:latest
#    restart: always
#    logging:
#      driver: json-file
#    networks:
#      elastic:
#        ipv4_address: "192.168.0.69"
#    ports:
#      - "22:22"
#    expose:
#      - "22"
#    volumes:
#      - ./homebridge/var/lib/homebridge:/homebridge:rw
networks:
  elastic: 
    driver: macvlan
    driver_opts: 
      parent: enp5s0
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.254

volumes:
  kbdata:
    driver: local
  uptime-kuma:
    driver: local