---
- name: Get Docker host info
  command: docker ps --format "{{ '{{.ID}}' }}'"
  register: docker_names

- name: Remove trailing single quote from container names
  set_fact:
    cleaned_docker_names: "{{ docker_names.stdout_lines | map('replace', \"'\", '') | list }}"

- name: Get info for each container
  docker_container_info:
    name: "{{ item }}"
  register: container_info
  loop: "{{ cleaned_docker_names }}"

- name: Generate index.http
  template:
    src: index.http.j2
    dest: "{{ haproxy_folder }}/index.http"
  register: index_http_result
  delegate_to: haproxy.local

- name: Backup Haproxy Config
  ansible.builtin.command:
    cmd: cp {{ haproxy_folder }}/haproxy.cfg {{ haproxy_folder }}/haproxy.cfg.backup
  register: haproxy_backup_result
  #when: index_http_result.changed
  delegate_to: haproxy.local

- name: Generate haproxy.conf
  template:
    src: haproxy.conf.j2
    dest: "{{ haproxy_folder }}/haproxy.cfg"
  register: haproxy_config_result
  #when: haproxy_backup_result.changed
  delegate_to: haproxy.local

- name: Restart service Haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  when: haproxy_config_result.changed
  delegate_to: haproxy.local

- name: Display docker names
  debug: 
    msg: "http://{{ item.key }}.rdprod.org:{{ item.value.expose }}/"
  loop: "{{ services | dict2items }}"

...