---
- name: Get Docker host info
  command: docker ps --format "{{ '{{.ID}}' }}'"
  register: docker_names

- name: Remove trailing single quote from container names
  set_fact:
    cleaned_docker_names: "{{ docker_names.stdout_lines | map('replace', \"'\", '') | list }}"

- name: Get info for each container
  docker_container_info:
    name: "{{ item }}"
  register: container_info
  loop: "{{ cleaned_docker_names }}"

- name: Generate index.http
  template:
    src: index.http.j2
    dest: /etc/haproxy/index.http
  register: index_http_result
  delegate_to: haproxy.local

- name: Backup Haproxy Config
  ansible.builtin.command:
    cmd: cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
  register: haproxy_backup_result
  #when: index_http_result.changed
  delegate_to: haproxy.local

- name: Generate haproxy.conf
  template:
    src: haproxy.conf.j2
    dest: /etc/haproxy/haproxy.cfg
  register: haproxy_config_result
  when: haproxy_backup_result.changed
  delegate_to: haproxy.local

- name: Restart service Haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  when: haproxy_config_result.changed
  delegate_to: haproxy.local

- name: Add Docker-Services in Cloudflare
  community.general.cloudflare_dns:
    zone: "rdprod.org"
    record: "{{ item.container.Name | regex_replace('^/', '') }}.rdprod.org"
    type: "A"
    value: "82.66.158.76"
    ttl: 300
    proxied: no
    state: "present"
    api_token: "SiRgv-1dGhN3DiB-10b2Id4CUiYJjpdassoQBtEA"
  when: index_http_result.changed
  loop: "{{ container_info.results }}"

- name: Add Other Services in Cloudflare
  community.general.cloudflare_dns:
    zone: "rdprod.org"
    record: "{{ item }}.rdprod.org"
    type: "A"
    value: "82.66.158.76"
    ttl: 300
    proxied: no
    state: "present"
    api_token: "SiRgv-1dGhN3DiB-10b2Id4CUiYJjpdassoQBtEA"
  loop:
    - rdmaster
    - freebox
    - rf
    - home
    - plex
    - homebridge
    - rdswitch
    - transmission

...