backup_dir: /opt
remote_name: rdmaster-opt:/rdmasteropt
backup_script_name: backup_opt.sh
cron_schedule: "0 0 * * *"
folder: "opt"
cf_token: "SiRgv-1dGhN3DiB-10b2Id4CUiYJjpdassoQBtEA"
cf_zone: "rdprod.org"
cf_ttl: "60"
public_ip: "82.66.158.76"
haproxy_folder: "/etc/haproxy"
ethernet_interface: ens18
ansible_connection: paramiko