---
- name: Make Basic Setup
  hosts: docker_host_runner
  become: yes
  roles:
    - ../roles/base_setup

- name: Deploy Docker Compose with custom image on docker_host
  hosts: docker_host_runner
  become: yes
  roles:
    - ../roles/docker_compose_deploy
  vars:
    app: "{{ docker_host_runner.app }}"
    services: "{{ docker_host_runner.services }}"
    networks: "{{ docker_host_runner.networks }}"
    volumes: "{{ docker_host_runner.volumes }}"

#- name: Update HAProxy on haproxy_host for docker_host
#  hosts: docker_host_runner 
#  become: yes
#  roles:
#    - ../roles/dyn_haproxy
#  vars:
#    services: "{{ docker_host_runner.services }}"
#    networks: "{{ docker_host_runner.networks }}"
#    volumes: "{{ docker_host_runner.volumes }}"
#    app: "{{ docker_host_runner.app }}"
#
#- name: Provision Cloudflare for Docker services for docker_host 
#  hosts: docker_host_runner 
#  become: yes
#  gather_facts: no
#  roles:
#    - role: ../roles/cloudflare
#  vars:
#    services: "{{ docker_host_runner.services }}"
#    networks: "{{ docker_host_runner.networks }}"
#    volumes: "{{ docker_host_runner.volumes }}"
#
#- name: Provision Cloudflare for Static services for docker_host 
#  hosts: docker_host_runner 
#  become: yes
#  gather_facts: no
#  roles:
#    - role: ../roles/cloudflare
#  vars:
#    services: "{{ docker_host_runner.static_cf_services }}"


