- name: Deploy Docker registry on docker_registry_host
  hosts: docker_registry_host
  become: yes
  roles:
    - role: ../roles/docker_compose_deploy
  vars:
    app: "{{ docker_registry_host.app }}"
    services: "{{ docker_registry_host.services }}"
    networks: "{{ docker_registry_host.networks }}"
    volumes: "{{ docker_registry_host.volumes }}"

- name: Update HAProxy on haproxy_host
  hosts: docker_host_runner 
  become: yes
  roles:
    - ../roles/dyn_haproxy
  vars:
    services: "{{ docker_registry_host.services }}"
    networks: "{{ docker_registry_host.networks }}"
    volumes: "{{ docker_registry_host.volumes }}"

- name: Provision Cloudflare for Docker registry 
  hosts: docker_registry_host
  become: yes
  gather_facts: no
  roles:
    - role: ../roles/cloudflare
  vars:
    services: "{{ docker_registry_host.services }}"
    networks: "{{ docker_registry_host.networks }}"
    volumes: "{{ docker_registry_host.volumes }}"
