---

- name: Deploy Docker Compose with custom image on mgmt_node
  hosts: mgmt_node
  become: yes
  roles:
    - ../roles/docker_compose_deploy
  vars:
    app: "{{ mgmt_node.app }}"
    services: "{{ mgmt_node.services }}"
    networks: "{{ mgmt_node.networks }}"
    volumes: "{{ mgmt_node.volumes }}"

- name: Update HAProxy on haproxy_host for mgmt_node
  hosts: mgmt_node 
  become: yes
  roles:
    - ../roles/dyn_haproxy
  vars:
    services: "{{ mgmt_node.services }}"
    networks: "{{ mgmt_node.networks }}"
    volumes: "{{ mgmt_node.volumes }}"
    app: "{{ mgmt_node.app }}"

- name: Provision Cloudflare for Docker services for mgmt_node 
  hosts: mgmt_node 
  become: yes
  gather_facts: no
  roles:
    - role: ../roles/cloudflare
  vars:
    services: "{{ mgmt_node.services }}"
    networks: "{{ mgmt_node.networks }}"
    volumes: "{{ mgmt_node.volumes }}"

- name: Provision Cloudflare for Static services for mgmt_node
  hosts: mgmt_node 
  become: yes
  gather_facts: no
  roles:
    - role: ../roles/cloudflare
  vars:
    services: "{{ mgmt_node.static_cf_services }}"

- name: Deploy Docker Compose with custom image on docker_host
  hosts: docker_host_runner
  become: yes
  roles:
    - ../roles/docker_compose_deploy
  vars:
    app: "{{ docker_host_runner.app }}"
    services: "{{ docker_host_runner.services }}"
    networks: "{{ docker_host_runner.networks }}"
    volumes: "{{ docker_host_runner.volumes }}"

- name: Update HAProxy on haproxy_host for docker_host
  hosts: docker_host_runner 
  become: yes
  roles:
    - ../roles/dyn_haproxy
  vars:
    services: "{{ docker_host_runner.services }}"
    networks: "{{ docker_host_runner.networks }}"
    volumes: "{{ docker_host_runner.volumes }}"
    app: "{{ docker_host_runner.app }}"

- name: Provision Cloudflare for Docker services for docker_host 
  hosts: docker_host_runner 
  become: yes
  gather_facts: no
  roles:
    - role: ../roles/cloudflare
  vars:
    services: "{{ docker_host_runner.services }}"
    networks: "{{ docker_host_runner.networks }}"
    volumes: "{{ docker_host_runner.volumes }}"

- name: Provision Cloudflare for Static services for docker_host 
  hosts: docker_host_runner 
  become: yes
  gather_facts: no
  roles:
    - role: ../roles/cloudflare
  vars:
    services: "{{ docker_host_runner.static_cf_services }}"


