---
- name: Montage des disques
  hosts: mgmt_node , docker_host_runner
  become: true
  vars:
  tasks:
  
  - name: Installation des paquets NFS
    apt:
      name:
        - nfs-common
      state: present

  - name: Création des points de montage
    file:
      path: "{{ item.mount_path }}"
      state: directory
    with_items: "{{ nfs_mounts }}"

  - name: Montage des disques NFS
    mount:
      path: "{{ item.mount_path }}"
      src: "{{ item.nfs_server }}:{{ item.mount_path }}"
      fstype: nfs
      opts: defaults
      state: mounted
    with_items: "{{ nfs_mounts }}"
...