---
- name: Update the apt-get package index
  apt:
    update_cache: yes

- name: Install necessary packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: Import Docker GPG key
  #shell: "sudo mkdir -m 0755 -p /etc/apt/keyrings ; curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  shell: "sudo mkdir -m 0755 -p /etc/apt/keyrings ; curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  ignore_errors: true

- name: Add Docker repository to apt sources
  #shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list'
  shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable" | sudo tee /etc/apt/sources.list.d/docker.list'
  ignore_errors: true
  delay: 30

- name: Update the apt-get package index
  apt:
    update_cache: yes

- name: Install Docker and Docker Compose
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - docker
      - docker-compose
      - containerd.io

...