version: '2'
services:

  registry:
    container_name: registry
    image: registry:latest
    restart: always
    logging:
      driver: json-file
    networks:
      elastic:
        ipv4_address: 192.168.0.61
    ports: ['5000:5000']
    expose: ['5000']
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_SECRET:
    volumes: ['./registry/auth:/auth:rw', './registry/data:/data:rw', './registry/config.yml:/etc/docker/registry/config.yml:rw']
  docker-registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:latest
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - REGISTRY_URL=http://registry.rdprod.org/
      - DELETE_IMAGES=true
    restart: always
    depends_on:
      - registry
    networks:
      elastic:
        ipv4_address: "192.168.0.62"
### Docker Networks
networks:
  elastic:
    driver: macvlan
    driver_opts:
      parent: enp5s0
    ipam:
      config: [{'subnet': '192.168.0.0/24', 'gateway': '192.168.0.254'}]

### Docker Volumes
volumes:
  registry:
    driver: local
