---
- name: Install Rclone
  apt:
    name: rclone
    state: present

# Configure Rclone
- name: Create Rclone config
  command: rclone config create rdmaster-opt s3 provider "Scaleway" env_auth "false" access_key_id "SCW0G4ZQ77S4RCYB30NZ" secret_access_key "5d1ddb60-0d8c-4835-a62f-58e007e3b299" region "fr-par" endpoint "s3.fr-par.scw.cloud" acl "private" storage_class "GLACIER"

# Create backup script
- name: Create backup script
  template:
    src: backup_opt.sh.j2
    dest: "{{ backup_dir }}/{{ backup_script_name }}"
    mode: '0755'

# Add backup script to crontab
#- name: Add backup script to crontab
#  cron:
#    name: "{{ backup_script_name }}"
#    job: "{{ backup_dir }}/{{ backup_script_name }}"
#    user: root
#    cron_file: "/etc/cron.daily/backup_opt"
#    state: present
#    minute: "0"
#    hour: "0"
#    day: "*"
#    month: "*"
#    weekday: "*"
#    backup: true

