image_name: "at-runner"
image_version: "latest"
#docker_registry: "https://registry.lab.un2ground.fr"
docker_registry: "registry.rdprod.org:5000"
#registry_username: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
#registry_password: "{{ lookup('env', 'REGISTRY_PASSWORD') }}"
registry_username: "darshaner"
registry_password: "05Darsh@ne"
build_dir: "/tmp/build"