app: "rdprod-services"
docker_host_runner:
  app: "rdprod-services"
  static_cf_services:
    rdmaster:
      proxied: false
    rf:
      proxied: false
    rdswitch:
      proxied: false
    freebox:
      proxied: true
    home:
      proxied: true
  services:
### Production Containers
    afp:
      container_name: afp
      hostname: afp
      image: mushanyoung/netatalk:latest
      restart: always
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.100"
      ports: 
        - "548:548"
      expose:
        - "548"
      environment: ['USER=darshaner','PASSWORD=05Darsh@ne']
      volumes: ['./afp/afp.conf:/conf/afp.conf', '/data:/data:rw', '/data-ssd:/data-ssd:rw', '/data-ssd2:/data-ssd2:rw', '/timemachine:/timemachine:rw']
      proxied: false

    homebridge:
      container_name: homebridge
      hostname: homebridge
      image: oznu/homebridge:latest
      restart: always
      mem_limit: 1024m
      mem_reservation: 256M
      cpus: 0.5
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.101"
      ports:
        - "8581:8581"
      expose:
        - "8581"
      volumes:
        - ./homebridge/var/lib/homebridge:/homebridge:rw
      proxied: true

    uptime:
      container_name: uptime
      hostname: uptime
      image: louislam/uptime-kuma:beta
      restart: always
      mem_limit: 1024m
      mem_reservation: 256M
      cpus: 0.5
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.102"
      ports:
        - "3001:3001"
      expose:
        - "3001"
      volumes:
        - ./uptime-kuma:/app/data:rw
      depends_on: 
        - kibana
      proxied: true

    plex:
      container_name: plex
      hostname: plex
      image: lscr.io/linuxserver/plex:latest
      restart: always
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.103"
      ports:
        - "32400:32400"
      expose:
        - "32400"
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        - VERSION=docker
      volumes:
        - ./plexdata/config:/config:rw
        - ./../data/Videos/TV Shows:/tv:rw
        - ./../data/Videos/Movies:/movies:rw
      proxied: true

    transmission:
      container_name: transmission
      hostname: transmission
      image: lscr.io/linuxserver/transmission:latest
      restart: always
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.104"
      ports:
        - "9091:9091"
        - "9413:9413"
        - "9413:9413/udp"
      expose:
        - "9091"
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        - USER=darshaner
        - PASS=2805Darsh@ne
        - PEERPORT=9413
      volumes:
        - ./transmission/:/config:rw
        - ./../data/Downloads:/downloads:rw
        - ./../data/Downloads/:/watch:rw
      proxied: true

### Lab Containers
    grafana:
      container_name: grafana
      hostname: grafana
      image: grafana/grafana:latest
      restart: always
      mem_limit: 512m
      mem_reservation: 256M
      cpus: 0.5
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.122"
      ports:
        - "3000:3000"
      expose:
        - "3000"
      #environment:
      volumes:
        - ./grafdata/grafana:/usr/share/grafana:rw
      depends_on:
        - es
      proxied: true

    es:
      container_name: es
      hostname: es
      image: elasticsearch:8.6.2
      restart: always
      mem_limit: 1024m
      mem_reservation: 256M
      cpus: 1
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.123"
      ports:
        - "9200:9200"
      expose:
        - "9200"
      healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3
      environment:
        - cluster.name=es-rajabaly
        - xpack.security.enabled=false
        - xpack.license.self_generated.type=basic
        - "discovery.type=single-node"
        - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
        - bootstrap.memory_lock=true
      volumes:
        - ./esdata/elasticsearch/:/usr/share/elasticsearch/:rw
      proxied: false

    kibana:
      container_name: kibana
      hostname: kibana
      image: kibana:8.6.2
      restart: always
      mem_limit: 1024m
      mem_reservation: 256M
      cpus: 0.5
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.124"
      ports:
        - "5601:5601"
      expose:
        - "5601"
      environment:
        - ELASTICSEARCH_HOSTS=http://es:9200
      volumes:
        - ./kbdata:/usr/share/kibana/data:rw
      depends_on:
        - es
      proxied: true

    homeassistant:
      container_name: homeassistant
      hostname: homeassistant
      image: "ghcr.io/home-assistant/home-assistant:stable"
      restart: always
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.125"
      ports:
        - "8123:8123"
      expose:
        - "8123"
      volumes:
        - ./homeassist/:/config:rw
        - /etc/localtime:/etc/localtime:ro
      privileged: true
      proxied: false

    gitlab:
      container_name: gitlab
      hostname: gitlab
      image: gitlab/gitlab-ce:latest
      restart: always
      logging:
        driver: json-file
      networks:
        elastic:
          ipv4_address: "192.168.0.126"
      ports:
        - "80:80"
        - "443:443"
        - "22:22"
      expose:
        - "80"
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://gitlab.rdprod.org'
      volumes:
        - ./gitlab/config:/etc/gitlab:rw
        - ./gitlab/logs:/var/log/gitlab:rw
        - ./gitlab/data:/var/opt/gitlab:rw
      proxied: true
    
  networks:
    elastic: 
      driver: macvlan
      driver_opts: 
        parent: enp5s0
      ipam:
        config:
          - subnet: 192.168.0.0/24
            gateway: 192.168.0.254

  volumes:
    kbdata:
      driver: local
    uptime-kuma:
      driver: local
    esdata:
      driver: local
    vaultdata:
      driver: local

  #  vault:
  #    container_name: vault
  #    image: vault:latest
  #    restart: always
  #    logging:
  #      driver: json-file
  #    networks:
  #      elastic:
  #        ipv4_address: 192.168.0.8
  #    ports: 
  #      - "8200:8200"
  #    expose:
  #      - "8200"
  #    environment:
  #      #- VAULT_DEV_ROOT_TOKEN_ID='05Darsh@ne'
  #      - VAULT_CLUSTER_ADDR='http://vault.rdprod.org:8200'
  #      - VAULT_API_ADDR='http://vault.rdprod.org/v1'
  #    volumes: 
  #      - ./vaultdata:/vault:rw
  #    cap_add:
  #      - IPC_LOCK
  #    command: server 


  #  at-runner:
  #    container_name: at-runner
  #    image: at-runner:latest
  #    restart: always
  #    logging:
  #      driver: json-file
  #    networks:
  #      elastic:
  #        ipv4_address: "192.168.0.69"
  #    ports:
  #      - "22:22"
  #    expose:
  #      - "22"
  #    volumes:
  #      - ./homebridge/var/lib/homebridge:/homebridge:rw